#!/bin/env bash
# This script is meant to run as a daily cron job to check if Microsoft's DBXs have changed
# It is primarily designed to find if https://github.com/pbatard/Mosby/blob/main/src/data.c needs an update.

github_url="https://api.github.com/"

# Retrieve the commit epoch from a GitHub URL or 0 if not available
get_commit_date() {
  url=$1
  if [[ "${url}" =~ ^"${github_url}" ]]; then
    parts=($(awk -F'contents/' '{ for(i=1;i<=NF;i++) print $i }' <<< ${url}))
    date_url="${parts[0]}commits?path=${parts[1]//\//%2F}&page=1&per_page=1"
    epoch="$(curl -s -L ${date_url} | python -m json.tool | grep -m1 \"date\": | sed -e 's/^.*\"date\":.*\"\(.*\)\".*/\1/' | date -f - +%s)"
  fi
  echo ${epoch:-0}
}

declare -A source=(
  ['https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/DBX/x86/DBXUpdate.bin']=1781077623
  ['https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/DBX/amd64/DBXUpdate.bin']=1781077623
  ['https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/DBX/arm/DBXUpdate.bin']=1740428422
  ['https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/DBX/arm64/DBXUpdate.bin']=1740428422
  ['https://api.github.com/repos/microsoft/secureboot_objects/contents/PostSignedObjects/Optional/DBX/DBXUpdateSVN.bin']=1781026739
)

for url in "${!source[@]}"; do
  timestamp=$(get_commit_date ${url})
  if (( $timestamp > ${source[${url}]} )); then
    BODY+="URL: ${url}\nDate: $(date -d @${timestamp})\nTimestamp: ${timestamp}\n"
  fi
done

if [[ $BODY ]]; then
 echo -e $BODY | mail -s "Microsoft DBX has been updated" pete@akeo.ie
fi
